const seedSearch = [
  {
    position: 'Developer',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 2,
    time: '2022-07-06',
    jobSchedules: 'Full Time',
    salary: '1000',
    title: 'Searching for a developer',
    createdAt: new Date(),
    updatedAt: new Date(),
    StatusId: 2,
    CountryId: 3,
    AreaId: 1,
    startDate: '2022-07-10',
    finishDate: '2022-07-30',
    searchTime: 20,
    ratingRecruiter: 0,
    candidates: 0,
  },
  {
    position: 'Chef',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 1,
    time: '2022-07-06',
    jobSchedules: 'Full Time',
    salary: '800',
    title: 'Chef vacancy',
    createdAt: new Date(),
    updatedAt: new Date(),
    StatusId: 2,
    CountryId: 2,
    AreaId: 1,
    startDate: '2022-07-10',
    ratingRecruiter: 0,
    candidates: 0,
  },
  {
    position: 'CM',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 3,
    time: '2022-07-06',
    jobSchedules: 'Full Time',
    salary: '1500',
    title: 'Big company looking for a new team of Marketing',
    createdAt: new Date(),
    updatedAt: new Date(),
    StatusId: 2,
    CountryId: 1,
    AreaId: 1,
    startDate: '2022-07-20',
    finishDate: '2022-07-30',
    searchTime: 10,
    ratingRecruiter: 0,
    candidates: 0,
  },
  {
    position: 'Administrador',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 1,
    time: '2022-07-06',
    jobSchedules: 'Full Time',
    salary: '700',
    title: 'We are hiring',
    createdAt: new Date(),
    updatedAt: new Date(),
    StatusId: 2,
    CountryId: 5,
    AreaId: 2,
    startDate: '2022-07-15',
    finishDate: '2022-08-1',
    searchTime: 17,
    ratingRecruiter: 0,
    candidates: 0,
  },
  {
    position: 'Seller',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 2,
    time: '2022-07-06',
    jobSchedules: 'Full Time',
    salary: '1000',
    title: 'Searching for a developer',
    createdAt: new Date(),
    updatedAt: new Date(),
    StatusId: 2,
    CountryId: 4,
    AreaId: 3,
    startDate: '2022-07-11',
    finishDate: '2022-07-21',
    searchTime: 10,
    ratingRecruiter: 0,
    candidates: 0,
  },
  {
    position: 'Productor',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 1,
    time: '2022-07-06',
    jobSchedules: 'Part Time',
    salary: '500',
    title: 'Estamos buscándote',
    createdAt: new Date(),
    updatedAt: new Date(),
    StatusId: 2,
    CountryId: 3,
    AreaId: 4,
    startDate: '2022-07-06',
    finishDate: '2022-07-15',
    searchTime: 9,
    ratingRecruiter: 0,
    candidates: 0,
  },
  {
    position: 'Project Manager',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 1,
    time: '2022-07-06',
    jobSchedules: 'Full Time',
    salary: '2500',
    title: 'Búsqueda de Project Manager tiempo completo',
    createdAt: new Date(),
    updatedAt: new Date(),
    StatusId: 2,
    CountryId: 2,
    AreaId: 5,
    startDate: '2022-07-21',
    finishDate: '2022-07-30',
    searchTime: 9,
    ratingRecruiter: 0,
    candidates: 0,
    RecruiterId: 1,
    ratingRecruiter: 10,
  },
  {
    position: 'Mensajero',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 5,
    time: '2022-07-06',
    jobSchedules: 'Full Time',
    salary: '1000',
    title: 'Mensajero en zona céntrica',
    createdAt: new Date(),
    updatedAt: new Date(),
    StatusId: 2,
    CountryId: 1,
    AreaId: 6,
    startDate: '2022-07-10',
    finishDate: '2022-07-17',
    searchTime: 7,
    ratingRecruiter: 0,
    candidates: 0,
    RecruiterId: 1,
    ratingRecruiter: 6,
  },
  {
    position: 'Sous Chef',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 2,
    time: '2022-07-06',
    jobSchedules: 'Full Time',
    salary: '2000',
    title: 'Restaurante por inaugurar busca Sous Chef',
    createdAt: new Date(),
    updatedAt: new Date(),
    StatusId: 2,
    CountryId: 3,
    AreaId: 9,
    startDate: '2022-07-15',
    finishDate: '2022-07-30',
    searchTime: 15,
    ratingRecruiter: 0,
    candidates: 0,
  },
  {
    position: 'Director de Recursos Humanos',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 1,
    time: '2022-07-06',
    jobSchedules: 'Full Time',
    salary: '1000',
    title: 'Empresa grande busca director de RRHH',
    createdAt: new Date(),
    updatedAt: new Date(),
    StatusId: 2,
    CountryId: 5,
    AreaId: 10,
    startDate: '2022-07-6',
    finishDate: '2022-07-9',
    searchTime: 3,
    ratingRecruiter: 0,
    candidates: 0,
  },
  {
    position: 'Enfermero',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 2,
    time: '2022-07-06',
    jobSchedules: 'Full Time',
    salary: '500',
    title: 'Enfermeros para Hospital Central',
    createdAt: new Date(),
    updatedAt: new Date(),
    StatusId: 2,
    CountryId: 4,
    AreaId: 11,
    startDate: '2022-07-11',
    finishDate: '2022-07-23',
    searchTime: 12,
    ratingRecruiter: 0,
    candidates: 0,
  },
  {
    position: 'Ingeniero Biomédico',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 2,
    time: '2022-07-06',
    jobSchedules: 'Full Time',
    salary: '2000',
    title: 'Ingeniero Biomédico',
    createdAt: new Date(),
    updatedAt: new Date(),
    StatusId: 2,
    CountryId: 3,
    AreaId: 1,
    startDate: '2022-07-14',
    finishDate: '2022-07-29',
    searchTime: 15,
    ratingRecruiter: 0,
    candidates: 0,
  },
  {
    position: 'Vendedor',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 2,
    time: '2022-07-06',
    jobSchedules: 'Part Time',
    salary: '800',
    title: 'Vendedor para call center',
    createdAt: new Date(),
    updatedAt: new Date(),
    StatusId: 2,
    CountryId: 2,
    AreaId: 6,
    startDate: '2022-07-12',
    finishDate: '2022-07-15',
    searchTime: 3,
    ratingRecruiter: 0,
    candidates: 0,
  },
  {
    position: 'Growth Manager',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 2,
    time: '2022-07-06',
    jobSchedules: 'Full Time',
    salary: '1000',
    title: 'Equipo de Marketing en crecimiento',
    createdAt: new Date(),
    updatedAt: new Date(),
    StatusId: 2,
    CountryId: 1,
    AreaId: 3,
    startDate: '2022-07-18',
    finishDate: '2022-07-25',
    searchTime: 7,
    ratingRecruiter: 0,
    candidates: 0,
  },
];

module.exports = seedSearch;
