const seedSearch = [
  {
    position: 'Developer',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 2,
    status: 'Open',
    time: '2022-07-06',
    jobSchedules: 'Full Time',
    salary: '1000',
    title: 'Searching for a developer',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    position: 'Chef',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 1,
    status: 'Open',
    time: '2022-07-06',
    jobSchedules: 'Full Time',
    salary: '800',
    title: 'Chef vacancy',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    position: 'CM',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 3,
    status: 'Open',
    time: '2022-07-06',
    jobSchedules: 'Full Time',
    salary: '1500',
    title: 'Big company looking for a new team of Marketing',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    position: 'Administrador',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 1,
    status: 'Open',
    time: '2022-07-06',
    jobSchedules: 'Full Time',
    salary: '700',
    title: 'We are hiring',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    position: 'Seller',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 2,
    status: 'Open',
    time: '2022-07-06',
    jobSchedules: 'Full Time',
    salary: '1000',
    title: 'Searching for a developer',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    position: 'Productor',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 1,
    status: 'Cerrada',
    time: '2022-07-06',
    jobSchedules: 'Part Time',
    salary: '500',
    title: 'Estamos buscándote',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    position: 'Project Manager',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 1,
    status: 'Open',
    time: '2022-07-06',
    jobSchedules: 'Full Time',
    salary: '2500',
    title: 'Búsqueda de Project Manager tiempo completo',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    position: 'Mensajero',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 5,
    status: 'Open',
    time: '2022-07-06',
    jobSchedules: 'Full Time',
    salary: '1000',
    title: 'Mensajero en zona céntrica',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    position: 'Sous Chef',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 2,
    status: 'Open',
    time: '2022-07-06',
    jobSchedules: 'Full Time',
    salary: '2000',
    title: 'Restaurante por inaugurar busca Sous Chef',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    position: 'Director de Recursos Humanos',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 1,
    status: 'Open',
    time: '2022-07-06',
    jobSchedules: 'Full Time',
    salary: '1000',
    title: 'Empresa grande busca director de RRHH',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    position: 'Enfermero',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 2,
    status: 'Open',
    time: '2022-07-06',
    jobSchedules: 'Full Time',
    salary: '500',
    title: 'Enfermeros para Hospital Central',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    position: 'Ingeniero Biomédico',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 2,
    status: 'Open',
    time: '2022-07-06',
    jobSchedules: 'Full Time',
    salary: '2000',
    title: 'Ingeniero Biomédico',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    position: 'Vendedor',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 2,
    status: 'Open',
    time: '2022-07-06',
    jobSchedules: 'Part Time',
    salary: '800',
    title: 'Vendedor para call center',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    position: 'Growth Manager',
    description:
      'Cake carrot cake soufflé powder tiramisu ice cream lollipop chocolate bar I love. Pastry pie topping I love cupcake. Marzipan I love tiramisu I love cotton candy carrot cake. Chocolate cake cake pudding halvah ice cream I love cupcake soufflé danish. Bear claw soufflé topping I love pudding. Donut I love macaroon dessert liquorice apple pie. Carrot cake fruitcake I love carrot cake sugar plum tiramisu chocolate gummi bears. Candy canes cupcake cake pie cake dragée pie chocolate chocolate cake.',
    vacancies: 2,
    status: 'Open',
    time: '2022-07-06',
    jobSchedules: 'Full Time',
    salary: '1000',
    title: 'Equipo de Marketing en crecimiento',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

module.exports = seedSearch;
