


const seedRecruiter = [
  {
    email: 'mari@mail.com',
    password: '1234',
    name: 'Mari',
    lastName: 'Ruiz',
    admin: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'john@hola.com',
    password: '1234',
    name: 'John',
    lastName: 'Doe',
    description:
    'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit​​, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 5,
    activeSearchs: 0,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'renato@hola.com',
    password: '1234',
    name: 'Renato',
    lastName: 'Booth',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit​​, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 8,
    activeSearchs: 0,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'salvatore@hola.com',
    password: '1234',
    name: 'Salvatore',
    lastName: 'Moses',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit​​, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 6,
    activeSearchs: 1,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'kasey@hola.com',
    password: '1234',
    name: 'Kasey',
    lastName: 'Roberson',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit​​, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 5,
    activeSearchs: 2,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'lula@hola.com',
    password: '1234',
    name: 'Lula',
    lastName: 'Vega',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit​​, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 7,
    activeSearchs: 9,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'bradly@hola.com',
    password: '1234',
    name: 'Bradly',
    lastName: 'Cummings',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit​​, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 1,
    activeSearchs: 0,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'susan1@hola.com',
    password: '1234',
    name: 'Susan',
    lastName: 'Walsh',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit​​, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 8,
    activeSearchs: 2,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'janis@hola.com',
    password: '1234',
    name: 'Janis',
    lastName: 'Weber',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit​​, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 5,
    activeSearchs: 4,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'susan@hola.com',
    password: '1234',
    name: 'Tabatha',
    lastName: 'Horne',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 6,
    activeSearchs: 1,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'scot@hola.com',
    password: '1234',
    name: 'Scot',
    lastName: 'Olsen',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 3,
    activeSearchs: 0,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'raquel@hola.com',
    password: '1234',
    name: 'Raquel',
    lastName: 'Flores',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 3,
    activeSearchs: 0,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'renaldo@hola.com',
    password: '1234',
    name: 'Renaldo',
    lastName: 'Rios',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 6,
    activeSearchs: 2,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'cortez@hola.com',
    password: '1234',
    name: 'Cortez',
    lastName: 'Moore',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 8,
    activeSearchs: 1,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'tiffany@hola.com',
    password: '1234',
    name: 'Tiffany',
    lastName: 'Malone',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 7,
    activeSearchs: 1,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'jack@hola.com',
    password: '1234',
    name: 'Jack',
    lastName: 'Yates',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 3,
    activeSearchs: 0,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'maynard@hola.com',
    password: '1234',
    name: 'Maynard',
    lastName: 'Doe',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit​​, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 5,
    activeSearchs: 0,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'courtney@hola.com',
    password: '1234',
    name: 'Courtney',
    lastName: 'Mueller',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit​​, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 8,
    activeSearchs: 0,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'cruz@hola.com',
    password: '1234',
    name: 'Cruz',
    lastName: 'Powers',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit​​, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 6,
    activeSearchs: 1,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'alisa@hola.com',
    password: '1234',
    name: 'Henry',
    lastName: 'Roberson',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit​​, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 5,
    activeSearchs: 2,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'jarrod@hola.com',
    password: '1234',
    name: 'Jarrod',
    lastName: 'Ramirez',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit​​, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 7,
    activeSearchs: 9,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'bradly1@hola.com',
    password: '1234',
    name: 'Bradly',
    lastName: 'Cummings',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit​​, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 1,
    activeSearchs: 0,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'francesco@hola.com',
    password: '1234',
    name: 'Francesco',
    lastName: 'Leach',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit​​, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 8,
    activeSearchs: 2,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'alberto@hola.com',
    password: '1234',
    name: 'Alberto',
    lastName: 'Guerrero',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit​​, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 5,
    activeSearchs: 4,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'luigi@hola.com',
    password: '1234',
    name: 'Luigi',
    lastName: 'Robertson',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 6,
    activeSearchs: 1,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'myra@hola.com',
    password: '1234',
    name: 'Myra',
    lastName: 'Pope',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 3,
    activeSearchs: 0,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'celeste@hola.com',
    password: '1234',
    name: 'Celeste',
    lastName: 'Massey',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 3,
    activeSearchs: 0,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'felipe@hola.com',
    password: '1234',
    name: 'Felipe',
    lastName: 'Rush',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 6,
    activeSearchs: 2,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'dylan@hola.com',
    password: '1234',
    name: 'Dylan',
    lastName: 'Burke',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 8,
    activeSearchs: 1,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'logan@hola.com',
    password: '1234',
    name: 'Logan',
    lastName: 'Brewer',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 7,
    activeSearchs: 1,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    email: 'alfreda@hola.com',
    password: '1234',
    name: 'Alfreda',
    lastName: 'Bishop',
    description:
      'Zombies reversus ab inferno, nam malum cerebro. De carne animata corpora quaeritis. Summus sit, morbo vel maleficia? De Apocalypsi undead dictum mauris. Hi mortuis soulless creaturas, imo monstra adventus vultus comedat cerebella viventium. Qui offenderit rapto, terribilem incessu. The voodoo sacerdos suscitat mortuos comedere carnem. Search for solum oculi eorum defunctis cerebro. Nescio an Undead zombies. Sicut malus movie horror.',
    rating: 3,
    activeSearchs: 0,
    admin: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

module.exports = seedRecruiter;
